# 01 Importing Libraries

# 02 Creating Dataframe

# 03 Initial Data Description

# 04 Removing Duplicates

# 05 Addressing Missing Values

# 06 Creating Data File for Project

## 01 Importing Libraries

In [1]:
# Import Analysis Libraries
import pandas as pd
import numpy as np
import os

## 02 Creating Dataframe

In [2]:
# Defining the main project path
proj = r'C:\Users\bfd_6\Documents\Career Foundry Project\Course Part 2\A6 Adv Analytics and Dashboards\Real Estate Project'

In [3]:
# Creating a data frame for the 2022 dataset
df_re = pd.read_excel(os.path.join(proj, '02 Data', 'Original Data', 'big_re_data_2022.xlsx'))

## 03 Initial Data Description

In [4]:
df_re.shape

(3222, 85)

In [5]:
df_re.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3222 entries, 0 to 3221
Data columns (total 85 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   geo_id                          3222 non-null   object
 1   us_county                       3222 non-null   object
 2   2022 total housing units        3222 non-null   int64
 3   2022 occupied housing units     3222 non-null   int64
 4   2022 vacant housing units       3222 non-null   int64
 5   2022 num_units -1_detached      3222 non-null   int64
 6   2022 num_units-1_attached       3222 non-null   int64
 7   2022 2 units                    3222 non-null   int64
 8   2022 3-4 units                  3222 non-null   int64
 9   2022 5-9 units                  3222 non-null   int64
 10  2022 10-19 units                3222 non-null   int64
 11  2022 20+ units                  3222 non-null   int64
 12  2022 mobile home                3222 non-null   int64
 13  2022 boat_rv_van_etc            3222 non-null   int64
 14  2022 built 2020+                3222 non-null   int64
 15  2022 built 2010-2019            3222 non-null   int64
 16  2022 built 2000-2009            3222 non-null   int64
 17  2022 built 1990-1999            3222 non-null   int64
 18  2022 built 1980-1989            3222 non-null   int64
 19  2022 built 1970-1979            3222 non-null   int64
 20  2022 built 1960-1969            3222 non-null   int64
 21  2022 built 1950-1959            3222 non-null   int64
 22  2022 built 1940-1949            3222 non-null   int64
 23  2022 built before 1940          3222 non-null   int64
 24  2022 1 room                     3222 non-null   int64
 25  2022 2 rooms                    3222 non-null   int64
 26  2022 3 rooms                    3222 non-null   int64
 27  2022 4 rooms                    3222 non-null   int64
 28  2022 5 rooms                    3222 non-null   int64
 29  2022 6 rooms                    3222 non-null   int64
 30  2022 7 rooms                    3222 non-null   int64
 31  2022 8 rooms                    3222 non-null   int64
 32  2022 9+ rooms                   3222 non-null   int64
 33  2022 no bedroom                 3222 non-null   int64
 34  2022 1 bedroom                  3222 non-null   int64
 35  2022 2 bedrooms                 3222 non-null   int64
 36  2022 3 bedrooms                 3222 non-null   int64
 37  2022 4 bedrooms                 3222 non-null   int64
 38  2022 5+ bedrooms                3222 non-null   int64
 39  2022 owner-occupied             3222 non-null   int64
 40  2022 renter-occupied            3222 non-null   int64
 41  2022 move-in 2021+              3222 non-null   int64
 42  2022 move-in 2018-2020          3222 non-null   int64
 43  2022 move-in 2010-2017          3222 non-null   int64
 44  2022 move-in 2000-2009          3222 non-null   int64
 45  2022 move-in 1990-1999          3222 non-null   int64
 46  2022 move-in before 1990        3222 non-null   int64
 47  2022 no vehicles available      3222 non-null   int64
 48  2022 1 vehicle available        3222 non-null   int64
 49  2022 2 vehicles available       3222 non-null   int64
 50  2022 3+ vehicles available      3222 non-null   int64
 51  2022 gas heat                   3222 non-null   int64
 52  2022 lp container heat          3222 non-null   int64
 53  2022 electric heat              3222 non-null   int64
 54  2022 oil or kerosene heat       3222 non-null   int64
 55  2022 coal or coke heat          3222 non-null   int64
 56  2022 wood heat                  3222 non-null   int64
 57  2022 solar heat                 3222 non-null   int64
 58  2022 other fuel heat            3222 non-null   int64
 59  2022 no fuel heat               3222 non-null   int64
 60  2022 no full bathroom           3222 non-null   int64
 61  2022 no full kitchen            3222 non-null   int64
 62  2022 no landline available      3222 non-null   object
 63  2022 1.00 or less occ per room  3222 non-null   int64
 64  2022 1.01 to 1.50 occ per room  3222 non-null   int64
 65  2022 1.51 or more occ per room  3222 non-null   int64
 66  2022 own_occ < $50k             3222 non-null   int64
 67  2022 own_occ $50k < $100k       3222 non-null   int64
 68  2022 own_occ $100k < $150k      3222 non-null   int64
 69  2022 own_occ $150k < $200k      3222 non-null   int64
 70  2022 own_occ $200k <$300k       3222 non-null   int64
 71  2022 own_occ $300k  - $500k     3222 non-null   int64
 72  2022 own_occ $500k - $1m        3222 non-null   int64
 73  2022 own_occ $1m+               3222 non-null   int64
 74  2022 mortgage                   3222 non-null   int64
 75  2022 no mortgage                3222 non-null   int64
 76  2022 rent producing units       3222 non-null   int64
 77  2022 gross rent < $500          3222 non-null   int64
 78  2022 gross rent $500 < $1k      3222 non-null   int64
 79  2022 gross rent $1k < $1.5k     3222 non-null   int64
 80  2022 gross rent $1.5k < $2k     3222 non-null   int64
 81  2022 gross rent $2k <$2.5k      3222 non-null   int64
 82  2022 gross rent $2.5k <$3k      3222 non-null   int64
 83  2022 gross rent $3k+            3222 non-null   int64
 84  2022 no rent paid               3222 non-null   int64
dtypes: int64(82), object(3)
memory usage: 2.1+ MB

In [6]:
pd.set_option('display.max_columns', None)
df_re.describe().map(lambda x: f"{x:0,.3f}")

,2022 total housing units,2022 occupied housing units,2022 vacant housing units,2022 num_units -1_detached,2022 num_units-1_attached,2022 2 units,2022 3-4 units,2022 5-9 units,2022 10-19 units,2022 20+ units,2022 mobile home,2022 boat_rv_van_etc,2022 built 2020+,2022 built 2010-2019,2022 built 2000-2009,2022 built 1990-1999,2022 built 1980-1989,2022 built 1970-1979,2022 built 1960-1969,2022 built 1950-1959,2022 built 1940-1949,2022 built before 1940,2022 1 room,2022 2 rooms,2022 3 rooms,2022 4 rooms,2022 5 rooms,2022 6 rooms,2022 7 rooms,2022 8 rooms,2022 9+ rooms,2022 no bedroom,2022 1 bedroom,2022 2 bedrooms,2022 3 bedrooms,2022 4 bedrooms,2022 5+ bedrooms,2022 owner-occupied,2022 renter-occupied,2022 move-in 2021+,2022 move-in 2018-2020,2022 move-in 2010-2017,2022 move-in 2000-2009,2022 move-in 1990-1999,2022 move-in before 1990,2022 no vehicles available,2022 1 vehicle available,2022 2 vehicles available,2022 3+ vehicles available,2022 gas heat,2022 lp container heat,2022 electric heat,2022 oil or kerosene heat,2022 coal or coke heat,2022 wood heat,2022 solar heat,2022 other fuel heat,2022 no fuel heat,2022 no full bathroom,2022 no full kitchen,2022 1.00 or less occ per room,2022 1.01 to 1.50 occ per room,2022 1.51 or more occ per room,2022 own_occ < $50k,2022 own_occ $50k < $100k,2022 own_occ $100k < $150k,2022 own_occ $150k < $200k,2022 own_occ $200k <$300k,2022 own_occ $300k - $500k,2022 own_occ $500k - $1m,2022 own_occ $1m+,2022 mortgage,2022 no mortgage,2022 rent producing units,2022 gross rent < $500,2022 gross rent $500 < $1k,2022 gross rent $1k < $1.5k,2022 gross rent $1.5k < $2k,2022 gross rent $2k <$2.5k,2022 gross rent $2.5k <$3k,2022 gross rent $3k+,2022 no rent paid
count,"3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000","3,222.000"
mean,"44,229.281","39,402.859","4,826.422","27,212.915","2,717.797","1,518.464","1,904.189","2,025.225","1,910.383","4,365.732","2,524.895",49.682,244.269,"3,606.361","5,982.540","5,845.506","5,835.020","6,506.300","4,538.942","4,355.131","2,036.719","5,278.493","1,077.779","1,336.523","4,025.907","7,073.730","8,399.130","7,764.040","5,283.821","3,919.319","5,349.032","1,193.197","4,795.826","11,167.393","17,339.241","7,633.777","2,099.847","25,551.739","13,851.120","1,855.968","8,004.363","13,398.573","7,505.157","4,261.453","4,377.345","3,304.111","12,887.380","14,542.656","8,668.712","18,395.395","1,898.836","15,742.238","1,658.097",31.472,585.174,97.528,192.050,802.069,156.003,324.226,"38,082.259",871.047,449.553,"1,449.124","2,031.669","2,413.237","2,788.626","5,056.840","6,097.833","4,308.188","1,406.222","15,661.118","9,890.621","13,138.294",948.351,"3,313.304","3,994.975","2,486.170","1,231.223",529.233,635.036,712.826
std,"130,512.478","120,103.411","11,602.324","68,874.859","12,517.015","7,542.502","8,440.261","8,892.042","8,651.432","27,450.569","4,635.368",149.690,798.634,"11,319.602","17,290.278","15,253.515","17,907.780","19,514.229","15,997.171","18,383.537","9,031.479","23,792.289","6,083.448","6,544.914","17,754.111","24,584.820","23,368.584","21,180.125","13,539.381","10,124.267","13,747.691","6,921.832","21,882.612","36,236.012","42,564.998","21,899.424","6,581.497","67,553.124","55,351.553","6,217.834","25,532.358","42,805.261","22,184.429","12,634.854","12,440.985","20,050.190","42,065.094","42,713.304","24,591.330","72,266.319","2,796.415","52,782.873","9,386.854",187.576,"1,020.487",705.809,677.734,"5,911.807",482.755,"1,261.298","112,791.802","5,168.053","3,451.374","2,755.668","3,869.528","5,128.415","6,520.162","13,255.598","18,957.688","22,804.102","11,907.909","44,513.007","23,591.027","53,810.503","3,006.654","8,482.160","15,676.720","13,436.041","8,495.147","4,411.683","6,377.135","1,643.339"
min,55.000,32.000,15.000,33.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,1.000,0.000,4.000,0.000,0.000,0.000,0.000,0.000,0.000,6.000,0.000,0.000,0.000,0.000,0.000,0.000,17.000,9.000,0.000,0.000,0.000,28.000,0.000,0.000,10.000,7.000,0.000,1.000,0.000,12.000,3.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,32.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
25%,"5,341.250","4,210.750",909.000,"3,936.750",37.000,71.000,87.250,67.000,29.000,40.250,462.000,0.000,6.000,257.250,548.000,696.250,642.000,863.500,487.000,405.000,224.000,496.000,54.000,71.000,281.000,782.250,"1,175.500","1,011.250",630.750,439.250,520.000,61.000,323.000,"1,373.750","2,483.250",750.000,170.000,"3,147.750","1,004.250",128.000,628.250,"1,256.250",896.500,556.000,657.250,223.000,"1,181.250","1,507.750","1,187.000",645.000,457.000,"1,181.000",6.000,0.000,68.000,0.000,11.000,12.000,14.000,26.000,"4,084.500",48.000,11.000,359.000,482.250,442.500,369.250,463.500,252.250,74.250,15.000,"1,344.250","1,728.250",814.250,143.000,418.000,116.000,8.000,0.000,0.000,0.000,149.000
50%,"12,374.000","10,021.000","1,921.000","8,923.500",170.000,246.000,289.000,240.000,125.500,183.000,"1,333.500",10.000,36.000,691.500,"1,528.500","1,834.500","1,595.000","2,023.000","1,168.500",934.000,497.500,"1,151.000",169.000,202.000,733.000,"1,887.000","2,727.000","2,354.000","1,575.500","1,033.000","1,319.000",186.000,774.500,"3,049.500","5,864.000","1,756.000",406.000,"7,325.500","2,579.500",351.000,"1,601.500","3,032.500","2,046.000","1,292.500","1,439.500",580.000,"2,920.500","3,660.500","2,711.000","2,420.000","1,066.500","3,801.500",51.000,0.000,240.000,0.000,44.000,46.000,50.000,85.000,"9,781.500",144.000,50.000,753.000,"1,041.000","1,040.500",977.000,"1,307.000",843.000,262.500,59.000,"3,549.000","3,707.500","2,159.000",337.000,"1,083.000",425.000,61.500,11.000,0.000,2.000,321.000
75%,"31,111.000","25,939.000","4,357.250","21,972.750",932.750,818.250,996.000,921.000,625.750,934.750,"2,856.000",40.000,137.000,"2,122.250","4,270.500","4,632.750","3,952.000","4,792.750","2,757.500","2,368.500","1,212.000","3,035.250",493.500,631.000,"2,075.250","4,737.500","6,768.000","5,879.250","4,098.500","2,845.250","3,650.500",537.500,"2,209.000","7,592.750","14,407.000","4,868.000","1,250.500","18,863.500","7,396.250","1,073.000","4,836.750","8,369.250","5,251.000","3,156.750","3,498.500","1,554.750","7,893.500","9,829.250","6,858.750","8,589.250","2,333.000","10,893.000",289.750,8.000,661.000,22.000,149.000,159.000,126.000,230.750,"25,454.750",394.750,158.000,"1,537.750","2,179.750","2,369.000","2,555.750","3,916.750","3,197.500","1,164.250",218.000,"10,441.000","8,440.500","6,733.750",770.000,"2,878.000","1,869.750",496.500,125.000,33.000,49.000,702.000
max,"3,599,561.000","3,363,093.000","236,468.000","1,724,662.000","417,343.000","211,609.000","235,831.000","281,112.000","275,500.000","720,178.000","89,292.000","3,544.000","15,604.000","262,103.000","401,362.000","347,370.000","427,785.000","499,914.000","518,564.000","702,463.000","350,540.000","636,554.000","231,164.000","215,882.000","568,082.000","764,272.000","625,457.000","522,574.000","286,176.000","199,115.000","215,572.000","261,849.000","689,093.000","1,068,353.000","1,009,021.000","447,655.000","123,590.000","1,552,164.000","1,810,929.000","144,392.000","587,277.000","1,206,560.000","652,683.000","395,292.000","376,889.000","601,621.000","1,128,954.000","1,171,605.000","771,452.000","2,147,846.000","55,952.000","1,157,040.000","233,928.000","5,760.000","13,247.000","20,665.000","22,098.000","194,162.000","15,178.000","52,679.000","2,990,763.000","213,417.000","158,913.000","63,255.000","73,579.000","101,558.000","151,216.000","300,493.000","400,315.000","821,457.000","411,740.000","1,073,905.000","478,259.000","1,761,865.000","67,852.000","171,407.000","393,654.000","471,272.000","322,973.000","165,835.000","208,077.000","49,064.000"

In [7]:
# Looking for columns with mixed data types
for col in df_re.columns.tolist():
    weird = (df_re[[col]].map(type) != df_re[[col]].iloc[0].apply(type)).any(axis = 1)
    if len (df_re[weird]) > 0:
        print(col)

2022 no landline available

There is one field with mixed data type.

## 04 Removing Duplicates

In [8]:
df_dupes = df_re[df_re.duplicated()]

In [9]:
print(df_dupes)

Empty DataFrame
Columns: [geo_id, us_county, 2022 total housing units, 2022 occupied housing units, 2022 vacant housing units, 2022 num_units -1_detached, 2022 num_units-1_attached, 2022 2 units, 2022 3-4 units, 2022 5-9 units, 2022 10-19 units, 2022 20+ units, 2022 mobile home, 2022 boat_rv_van_etc, 2022 built 2020+, 2022 built 2010-2019, 2022 built 2000-2009, 2022 built 1990-1999, 2022 built 1980-1989, 2022 built 1970-1979, 2022 built 1960-1969, 2022 built 1950-1959, 2022 built 1940-1949, 2022 built before 1940, 2022 1 room, 2022 2 rooms, 2022 3 rooms, 2022 4 rooms, 2022 5 rooms, 2022 6 rooms, 2022 7 rooms, 2022 8 rooms, 2022 9+ rooms, 2022 no bedroom, 2022 1 bedroom, 2022 2 bedrooms, 2022 3 bedrooms, 2022 4 bedrooms, 2022 5+ bedrooms, 2022 owner-occupied, 2022 renter-occupied, 2022 move-in 2021+, 2022 move-in 2018-2020, 2022 move-in 2010-2017, 2022 move-in 2000-2009, 2022 move-in 1990-1999, 2022 move-in before 1990, 2022 no vehicles available, 2022 1 vehicle available, 2022 2 vehicles available, 2022 3+ vehicles available, 2022 gas heat, 2022 lp container heat, 2022 electric heat, 2022 oil or kerosene heat, 2022 coal or coke heat, 2022 wood heat, 2022 solar heat, 2022 other fuel heat, 2022 no fuel heat, 2022 no full bathroom, 2022 no full kitchen, 2022 no landline available, 2022 1.00 or less occ per room, 2022 1.01 to 1.50 occ per room, 2022 1.51 or more occ per room, 2022 own_occ < $50k, 2022 own_occ $50k < $100k, 2022 own_occ $100k < $150k, 2022 own_occ $150k < $200k, 2022 own_occ $200k <$300k, 2022 own_occ $300k  - $500k, 2022 own_occ $500k - $1m, 2022 own_occ $1m+, 2022 mortgage, 2022 no mortgage, 2022 rent producing units, 2022 gross rent < $500, 2022 gross rent $500 < $1k, 2022 gross rent $1k < $1.5k, 2022 gross rent $1.5k < $2k, 2022 gross rent $2k <$2.5k, 2022 gross rent $2.5k <$3k, 2022 gross rent $3k+, 2022 no rent paid]
Index: []

There are no duplicate rows in the dataframe. The dataframe is empty.

## 05 Addressing Missing Values

In [9]:
pd.set_option('display.max_rows', None)
df_re.isnull().sum()

geo_id                            0
us_county                         0
2022 total housing units          0
2022 occupied housing units       0
2022 vacant housing units         0
2022 num_units -1_detached        0
2022 num_units-1_attached         0
2022 2 units                      0
2022 3-4 units                    0
2022 5-9 units                    0
2022 10-19 units                  0
2022 20+ units                    0
2022 mobile home                  0
2022 boat_rv_van_etc              0
2022 built 2020+                  0
2022 built 2010-2019              0
2022 built 2000-2009              0
2022 built 1990-1999              0
2022 built 1980-1989              0
2022 built 1970-1979              0
2022 built 1960-1969              0
2022 built 1950-1959              0
2022 built 1940-1949              0
2022 built before 1940            0
2022 1 room                       0
2022 2 rooms                      0
2022 3 rooms                      0
2022 4 rooms                      0
2022 5 rooms                      0
2022 6 rooms                      0
2022 7 rooms                      0
2022 8 rooms                      0
2022 9+ rooms                     0
2022 no bedroom                   0
2022 1 bedroom                    0
2022 2 bedrooms                   0
2022 3 bedrooms                   0
2022 4 bedrooms                   0
2022 5+ bedrooms                  0
2022 owner-occupied               0
2022 renter-occupied              0
2022 move-in 2021+                0
2022 move-in 2018-2020            0
2022 move-in 2010-2017            0
2022 move-in 2000-2009            0
2022 move-in 1990-1999            0
2022 move-in before 1990          0
2022 no vehicles available        0
2022 1 vehicle available          0
2022 2 vehicles available         0
2022 3+ vehicles available        0
2022 gas heat                     0
2022 lp container heat            0
2022 electric heat                0
2022 oil or kerosene heat         0
2022 coal or coke heat            0
2022 wood heat                    0
2022 solar heat                   0
2022 other fuel heat              0
2022 no fuel heat                 0
2022 no full bathroom             0
2022 no full kitchen              0
2022 no landline available        0
2022 1.00 or less occ per room    0
2022 1.01 to 1.50 occ per room    0
2022 1.51 or more occ per room    0
2022 own_occ < $50k               0
2022 own_occ $50k < $100k         0
2022 own_occ $100k < $150k        0
2022 own_occ $150k < $200k        0
2022 own_occ $200k <$300k         0
2022 own_occ $300k  - $500k       0
2022 own_occ $500k - $1m          0
2022 own_occ $1m+                 0
2022 mortgage                     0
2022 no mortgage                  0
2022 rent producing units         0
2022 gross rent < $500            0
2022 gross rent $500 < $1k        0
2022 gross rent $1k < $1.5k       0
2022 gross rent $1.5k < $2k       0
2022 gross rent $2k <$2.5k        0
2022 gross rent $2.5k <$3k        0
2022 gross rent $3k+              0
2022 no rent paid                 0
dtype: int64

There are no missing values in the dataframe

## 06 Creating Data File for Project

In [10]:
# Exporting pkl file to prepared data folder for the products data set with no dups or missing values
df_re.to_pickle(os.path.join(proj, '02 Data', 'Prepared Data', 'real_estate_data_2022.pkl'))